### PR TITLE
Auto-installer comments out GRUB_TERMINAL_OUTPUT

### PR DESCRIPTION
**Pull request by LinuxHeki**
Hi! Your theme is so cool! But when I installed with auto-installer it didn't work so I decided to fix it. I also added contributors in the `install.py` comment at the top and updated version.

### CODE REVIEW

**Comment by vandalsoul** [comment]
Hey @LinuxHeki 
This script isn't actually compatible with fedora ( I guessing you are a fedora user 😅) and I did fix this issue in the installation script on my other [grub theme](https://github.com/vandalsoul/dedsec-grub2-theme/blob/main/install.py). I was actually planning to update the script in the next theme update which might be this week 🤔, not sure.

And yeah thanks for the contribution, this might help a lot of users 😉

I will merge this after I review the changes 👍

**Comment by LinuxHeki** [comment]
Not compatible? Run a script and comment out one thing is not compatible? Of course it is! It has grub2 support! And how did you know that I'm a feora user?

**Comment by vandalsoul** [comment]
@LinuxHeki I think you got me wrong. I was talking about my current [installation script](https://github.com/vandalsoul/darkmatter-grub2-theme/blob/main/install.py) in this main repo, yours works fine, I checked it just now. And now about Fedora, as far as I have seen Fedora seems to be the only one that doesn't show grub theme out of the box _( ie due to the line `GRUB_TERMINAL_OUTPUT="console"`)_ that's how I guessed 🤷‍♂️

**Comment by LinuxHeki** [comment]
Yes I know. Running a script and then commenting one line seems compatible to me.

**Pull request merged**
